# Form implementation generated from reading ui file 'adminEditProduct.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from backend.notification import Notification
from backend.product import Product
from backend.utils.util import utils
from PyQt6.QtGui import QPixmap  # or PyQt6.QtGui if using PyQt6



class Ui_MainWindow(object):
    def setupUi(self, MainWindow, product):
        self.product = product
        self.mainWindow = MainWindow
        self.myProduct = Product()
        print(self.product)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(427, 625)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image = QtWidgets.QLabel(parent=self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(40, 30, 351, 261))
        self.Image.setStyleSheet("background : gray")
        self.Image.setText("")
        self.Image.setObjectName("Image")
        self.Name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(40, 320, 351, 41))
        self.Name.setObjectName("Name")
        self.Price = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Price.setGeometry(QtCore.QRect(40, 390, 351, 41))
        self.Price.setObjectName("Price")
        self.Stocks = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Stocks.setGeometry(QtCore.QRect(40, 460, 351, 41))
        self.Stocks.setObjectName("Stocks")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 300, 49, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 370, 49, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 440, 49, 16))
        self.label_3.setObjectName("label_3")
        self.SaveChanges = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SaveChanges.setGeometry(QtCore.QRect(40, 510, 351, 41))
        self.SaveChanges.setObjectName("SaveChanges")
        self.close = QtWidgets.QPushButton(parent=self.centralwidget)
        self.close.setGeometry(QtCore.QRect(40, 560, 351, 41))
        self.close.setObjectName("close")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

     
        self.Image.setPixmap(QPixmap("frontend/product_img/" + self.product['image']))
        self.Image.setScaledContents(True)  

        self.Name.setText(product['name'])  
        self.Price.setText(str(product['price']))  
        self.Stocks.setText(str(product['stocks']))

        self.SaveChanges.clicked.connect(self.updateProduct)
        self.close.clicked.connect(MainWindow.showAdminProducts)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def updateProduct(self):
        myNotification = Notification()
        currentProduct = self.myProduct.getProduct(self.product['id'])
        updatedProduct = {
            "product_id" : self.product['id'] ,
            "name" : self.Name.text() ,
            "price" : int(self.Price.text()) ,
            "stocks" : int(self.Stocks.text()) 
        }

        header = ""
        message = "product: " + self.Name.text()
        icon = "success"


        if currentProduct["stocks"] != int(updatedProduct["stocks"]):
            header = "Restock Product"
        elif currentProduct["name"] != updatedProduct["name"]:
            header = "Product Change Name"
        elif currentProduct["price"] != int(updatedProduct["price"]):
            header = "Product Change Price"
        else:
            header = "Saved Product"
            return

        myNotification.addNotifications({
            "header" : header,
            "message" : message,
            "icon" : icon
        })

        self.myProduct.updateProduct(updatedProduct)
        utils.alertSuccess("Product updated")
        self.mainWindow.showAdminProducts()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "name: "))
        self.label_2.setText(_translate("MainWindow", "price: "))
        self.label_3.setText(_translate("MainWindow", "stocks:"))
        self.SaveChanges.setText(_translate("MainWindow", "Save Changes"))
        self.close.setText(_translate("MainWindow", "Close"))
